services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: "oncokb_core_test"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    # Workaround to resolve error (https://stackoverflow.com/questions/50424900/error-client-does-not-support-authentication-protocol-requested-by-server-cons)
    # TLDR; we need to upgrade our MySQL connect from v5 to v8, so that everything works properly with mysql v8+
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: bind
        source: ../mysql_dumps
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - testnet
  maven:
    image: 3.8.6-eclipse-temurin-8
    container_name: maven-test-runner
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${PWD}:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["sh", "-c", "./unit_test/scripts/run_test.sh"]
    networks:
      - testnet

networks:
  testnet:
