name: Build/Push no-frontend docker image
on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: "Tag name to use for the image must start with a v"
        required: true
        type: string
  release:
    types: [published]
jobs:
  main:
    if: github.repository == 'oncokb/oncokb'
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Update Pom
        env:
          TAG_NAME: ${{ inputs.tag-name || github.event.release.tag_name }}
        run: |
          mvn --batch-mode versions:set -DnewVersion=${TAG_NAME:1}-no-frontend -DgenerateBackupPoms=false

      - name: Generate docker image for public-api build
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          TAG_NAME: ${{ inputs.tag-name || github.event.release.tag_name }}
          REPOSITORY: mskcc/oncokb
        run: |
          mvn -ntp package -P public-api,image-build \
          -DskipTests \
          -Djib.to.image="${REPOSITORY}:${TAG_NAME:1}-no-frontend" \
          -Djib.to.auth.username=$DOCKER_USERNAME \
          -Djib.to.auth.password=$DOCKER_PASSWORD
